### ISSUE TITLE
Dataset recoding improvements

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding#11]
- [x] Modify GUI. We will implement something like a two modes interface. Update button displays a panel to decide the new metadata. Previous fields are disabled. Get Data is hidden and two buttons show up: Confirm Update or Cancel
- [x] Validations
   - [x] If fields are the same a warning is displayed. No action is performed.
   - [x] If there is data associated with the new metadata. A warning message is displaying explaining the issue and asking for confirmation.
- [x] Migrate to 2.26. It should be working fine but double check it. In general, it would be good if we develop in this environment
- [x] Multilanguage
   - [x] Add languages support: Spanish, French, Arabic
   - [x] Connect to POEditor (@adrianq to discuss with @ifoche best approach)
- [x] Clean manifest (authors to team, etc)
- [x] Remove .project
- [x] Deploy at NRC dev server.

**Comment by adrianq** [comment]
Mockups about new GUI look&feel:

![screenshot from 2017-03-09 15 29 07](https://cloud.githubusercontent.com/assets/6850223/23756915/29fbdb66-04dd-11e7-9af0-62790a6bc372.png)

Some notes about the workflow as discussed this morning:
- Update button is only enabled if 'Get Data' has been previously performed
- If 'Get Data' is executed and afterward any field is changed, Update button is disabled
- Once Update is press we go into the second screen. Find as follow:

![screenshot from 2017-03-09 15 33 51](https://cloud.githubusercontent.com/assets/6850223/23757136/e02d0e8c-04dd-11e7-9297-5fa3048a1ad5.png)

- 'Get Data' button is hidden
- As discussed we should differentiate the two 'Update' buttons (Update in the first and second screen). Maybe with an icon or a different name?
- If Cancel is pressed, we come back to the first screen.
- If Update is pressed we perform the update

We are probably missing some workflows and corner cases but I guess we will be discovering and solving them during the implementation phase.

**Comment by adrianq** [comment]
[This issue](https://github.com/EyeSeeTea/dataset-recoding/issues/5) provides some information about current implementation. In case it is of any help...

**Comment by tokland** [comment]
Some screenshots to see the two-step process:

![rec1](https://cloud.githubusercontent.com/assets/24643/24044000/8c7ffa5a-0b19-11e7-972f-44a8e0af174a.png)
![rec2](https://cloud.githubusercontent.com/assets/24643/24044001/8c9a7b46-0b19-11e7-974a-26f08b4d1551.png)
![rec3](https://cloud.githubusercontent.com/assets/24643/24044002/8ca88de4-0b19-11e7-8e4d-f8406b176ad4.png)

For the sake of simplicity:

- The warning for same metadata is done with JS's alert.
- The confirmation dialog if there exists datavalues is done with JS's confirm.

To discuss on the next meeting:
- After a recoding, what values should show the first form? (the same we had OR the one we just saved, OR clean it completely)

**Comment by adrianq** [comment]
@tokland Looks really good!

Re your question, I wouldn't show the old values for sure. It would be too confused for the user, right? Maybe the ones we have just saved so he can start the process again if he wants to. Unless it is too difficult from a technical point of view. What do u think?

**Comment by adrianq** [comment]
My task in this card is done. I have created and configured the project in POEditor and give it a try to the link between GitHub json file and the platform. Working nicely. I just have to update the link to development branch once we merge this PR.

Finally, there is no need to deploy the web app in their servers. They will be doing it by themselves. I just have to release in this repo and in the blessed one once we are done.

**Comment by adrianq** [comment]
@tokland Forget what I said before. I actually like the current behaviour after you click update but let's discuss it tomorrow.

btw, are you getting this errors?
![screenshot from 2017-03-19 15 10 32](https://cloud.githubusercontent.com/assets/6850223/24082000/44daf03a-0cb6-11e7-8bef-8451f420caec.png)

**Comment by tokland** [comment]
What DHIS version are you running? On 2.26 I get those two files corretly:

Request URL:http://dhis26local:9026/dhis-web-commons/font-awesome/css/font-awesome.min.css
Status Code:200 OK

Request URL:http://dhis26local:9026/api/apps/dataset-recoding-old/include/bootstrap-3.3.1-dist/css/bootstrap.min.css
Status Code:200 OK

I do get two errors on the console at app boot, one of the icons on the app menu is not found:

```
dhis-web-menu-management.png:1 GET http://dhis26local:9026/icons/dhis-web-menu-management.png 404 (Not Found)
program.png:1 GET http://dhis26local:9026/api/apps/icons/program.png 404 (Not Found)
```
When using Spanish, the filter placeholder (rendered by dhis-entry), shows the escaped utf8 string: "Filtrar en la secci\u00F3n". I'll see if that can be solved.

**Comment by adrianq** [comment]
Finally, js error has to do with NRC metadata (customs forms). [Issue created](https://github.com/EyeSeeTea/nrcwebapps/issues/4) although we are not taking care of this for the moment.
