### ISSUE TITLE
Implement logging feature

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding#12]
- [x] Implement logs 
   - [x] Investigate with @josemp10 best way to implement this feature. Auditing api can be found [here](https://docs.dhis2.org/master/en/developer/html/webapi_auditing.html). Problably we will have to save this information using the app store api
   - [x] Implement a div at the top hidden by default. Add button or link to show the content. It should allow scrolling.
   - [x] Retrieve logging from the server.
   - [x] Persist our own logs
   - [x] Define how much information will be displayed and how to display/load so we don't have any performance issue

**Comment by adrianq** [comment]
Finally, auditing doesn't seem to be an option for us. We will have to store the logs in the app store and retrieve them. @tokland we need to discuss tomorrow what could be the best approach so we don't get into performance issue due to retrieving or displaying too much information

**Comment by tokland** [comment]
Ok. Yes, we'll need to segment the data logs somehow.
