### ISSUE TITLE
Review i18 files

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding#29]
We need to have the same terms in every i18n file otherwise POEditor considers not found translations as missing. If possible it would be great if we only have the terms that are needed for the app so the translator doesn't have to deal with terms that are not actually used.

It would be great if we can create a PR to development with this so that I can patch 0.2.0 release

**Comment by tokland** [comment]
[feature/wizard-steps123]

This really needed a clean up, now we have 60 keys for all languages, same order, using english for the missing translations
