### ISSUE TITLE
Implement Data Input Periods functionality

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding#31]
Once we discussed what should be the expected behaviour (and if there is any bug) we will have to implement this feature.

For now I will take care of this trying to understand these bits

**Comment by adrianq** [comment]
I already know how it works will let you know on our next meeting

**Comment by tokland** [comment]
[feature/wizard-steps123]

Each type of period has different codes hardcoded in maintenance-app, nothing that can be reused. So, what I have done to make it simple: regardless the _periodType_ value, monthly period entries are created, covering from project.startDate to project.endDate (both included).

**Comment by adrianq** [comment]
@tokland I have moved this card back to ready after discussing this feature with the client. In order to provide a better user experience, he suggested substituting this component with two components that will be used to introduce the start and end date. I think we can reuse this component:
![screenshot from 2017-05-06 00 57 28](https://cloud.githubusercontent.com/assets/6850223/25768029/12abc182-31f7-11e7-83a8-82f7146d414b.png)

If the dataset is linked to a project these components will be prefilled with the start and end date of the project as we discussed. Behind the scenes, we will process that information and fill the dataset properly before persisting. 

Again, I will wait for this to be done before merging this [PR](https://github.com/EyeSeeTea/dataset-configuration/pull/36)

Thanks!

**Comment by adrianq** [comment]
Something else I was misunderstanding this component behaviour. 
![screenshot from 2017-05-06 01 15 39](https://cloud.githubusercontent.com/assets/6850223/25768277/8bff678a-31f9-11e7-897d-24205db636e9.png)

Dates on the left are the dates you can potentially register data for, i.e. for this dataset I can register data (using data entry app) for April and May 2017. 

Dates on the right specify when I am allowed to register that information, i.e. I am allowed to register data for April between 31st March and 30th May. If I go to data entry the 1st of June and choose this dataset, I won't see April as an option in the Period drop-down list. However if I go, let's say, the 28th May I will be still allowed to introduce data for April and, therefore, I will see April as an option in the Period drop-down list.

That said, what we did was wrong. We should allow the user to register data for this project anytime between the start and end date. So left column is correct but right column should always be the start and end date of the project. Example -> Project Start Date: 5th April - Project End Date: 16th June This is how it should look:
![screenshot from 2017-05-06 01 26 47](https://cloud.githubusercontent.com/assets/6850223/25768390/1d650292-31fb-11e7-82d4-b4379c8f0b30.png)

If you read my previous comment we are not gonna be using this component anymore. I am not sure how this information is stored in the dataset bean that will be used to persist the information in DHIS but I just want to give you all the information :)

**Comment by tokland** [comment]
- [ ] To confirm: What do we do when `periodType != "Monthly"`. As as I mentioned before,  it's doable but not trivial to generate periods for all types. Current behaviour: creates montly periods from start to end for any value of `periofType`.

**Comment by tokland** [comment]
![screenshot from 2017-05-08 13-49-13](https://cloud.githubusercontent.com/assets/24643/25802997/3408b434-33f5-11e7-96d9-573eb5fcacb8.png)

**Comment by adrianq** [comment]
@tokland New components look great. I will create a specific card to deal with data input start and end date when periodType != monthly. I don't want to spend more time with this and we can probably review it during following milestones.
